### ISSUE TITLE
Add support for mathematical expressions written in Latex 

### ISSUE THREAD

**Issue by fsdias** [henrikingo/impress.js#11]
Hi 

It seems that vanilla impress.js does not have support for mathematical expressions written in latex [1]. However it seems that some users have managed to add support for latex expressions  with Mathjax [2].  Reveal.js has also followed that route [3]. 

I think it would be great if could you add a Mathjax plugin to your fork.

Thanks for your work, I think it has made impress.js easier to use and more accessible to end users.

[1] https://github.com/impress/impress.js/issues/376
[2] http://www.lsv.ens-cachan.fr/~schmitz/pub/impress.js/#/step-2
[3] https://github.com/hakimel/reveal.js/#mathjax

**Comment by henrikingo** [comment]
Thanks for this suggestion @fsdias! I don't have experience with mathjax, but on the face of it, this looks like an excellent idea! Mathjax could definitively be added to extras/

If nobody else shows up with a PR soon, I'll definitively do it myself.

**Comment by fsdias** [comment]
Great! There's another library that apparently can do the same. I'm sharing the link in case it is useful:

https://khan.github.io/KaTeX/

**Comment by fsdias** [comment]
Mathjax support has been added to hovercraft. Maybe the code can be useful here

https://github.com/regebro/hovercraft/commit/0def2accb53c9f2486c6185185d3d6641bdc4e6c

**Comment by henrikingo** [comment]
This commit adds MathJax.js support: https://github.com/henrikingo/impress.js/commit/9595627685dfc793df6f71cfca35ce9dd6d13b74

Worked like a charm, the only quirk was that MathJax is so big, that I had to pull out the extras/ directory into a separate repo, and use it as a git submodule instead. That's ok, I had planned to refactor it like that anyway.

Demo: http://henrikingo.github.io/impress.js/examples/classic-slides/#/step-11

Thanks for suggesting this!

**Comment by fsdias** [comment]
Thanks a lot, I just tested it and it works perfectly
