### ISSUE TITLE
Make possible to include markdown file

### ISSUE THREAD

**Issue by Sigmun** [henrikingo/impress.js#15]
do you know if there is a way to include markdown file within my presentation (no precompilation) ?

**Comment by henrikingo** [comment]
Hi @Sigmun 

Yes, that's exactly what the Markdown.js support in this repo does. See
https://github.com/henrikingo/impress.js/blob/myfork/examples/markdown/index.html

**Comment by Sigmun** [comment]
Hi @henrikingo, I know that you can write in Markdown within the html file. I wonder if it is possible to include the content of a separated markdown file.

**Comment by henrikingo** [comment]
Ah, right.

No, in that case I recommend you to indeed use either hovercraft or markdown-impress.

The approach in my impress.js repo is based on the idea that you'd want to write the majority of your content in Markdown, but still retain the option of touching the HTML or CSS a little bit, when needed.
