### ISSUE TITLE
specify a class in markdown

### ISSUE THREAD

**Issue by lesion** [henrikingo/impress.js#16]
hi,
is there a way to specify a class to a markdown block? I want to use `substep` and `highlight` syntax inside a markdown block, example:

```sh
   * this is a li {class: substep}
 
     {class: c}
     var a = ciao
```

**Comment by henrikingo** [comment]
Hi @lesion 

I don't know that it is possible. But this seems like a question you should ask Markdown.js developers, here: https://github.com/evilstreak/markdown-js
