### ISSUE TITLE
'extras' folder is empty

### ISSUE THREAD

**Issue by WulfricLee** [henrikingo/impress.js#18]
In example **'classic-slides'**, references to highlight.pack.js, mermaid.min.js, markdown.js, MathJax.js all not found.

**Comment by henrikingo** [comment]
Hi Glenn

The extras/ folder is now a git module. Their contents is found here: https://github.com/impress/impress-extras

You need to use `git clone --recursive https://github.com/impress/impress.js` when cloning impress.js to have the module cloned too. Alternatively, if you already cloned the repo and want to clone the submodule after the fact:

    git submodule init
    git submodule update

Did you find a link in classic-slides that is now a dead end? I tried to look, but didn't see any.

**Comment by WulfricLee** [comment]
@henrikingo Thank you for reply, and that's really helpful, I fixed my own work by grab these xxx.js from their official web sites. 
I browsed your **['classic-slides'](http://henrikingo.github.io/impress.js/examples/classic-slides/#/step-3)** demo that distributed on github.io and I didn't see any dead link also.
And I got to say, Henrik, your **'classic-slides'** demo is the most practical demo I ever seen so far, any also your **substep** plugin, it's like redefined impress.js, your works really helped me solving a lot of troubles, thank you very much :)

**Comment by henrikingo** [comment]
Thanks for the feedback, I'm glad you like it!

Btw, all my work is now merged into upstream impress.js as well. I just haven't added a mention to the README in my fork yet. I'm now updating the official impress.js and the myfork branch we're discussing here will not be updated any longer.
