### ISSUE TITLE
Can't work with impress.js-0.6.0

### ISSUE THREAD

**Issue by jmecn** [henrikingo/impress.js#9]
Your markdown.js addon works very great with 0.5.3, it is just what I'm looking for, but when I update impress.js to 0.6.0 it didn't work.

**Comment by henrikingo** [comment]
Hi @jmecn 

Thanks for trying out my plugin integration work.

Can you give more detail on the steps you've taken? The Markdown demo certainly still works over here: http://henrikingo.github.io/impress.js/examples/markdown/

Note that [my fork](https://github.com/henrikingo/impress.js/) contains all of upstream 0.6.0 that I considered worth taking, so it is based on impress.js 0.6.0. [The demo is part of that repo as well.](https://github.com/henrikingo/impress.js/tree/myfork/examples/markdown)

**Comment by jmecn** [comment]
My fault, I didn't read all the source code 4 days ago.

More details:

I saw the comments of impress.js in your fork is still 0.5.3,  so I think maybe you use 0.5.3. But then I read the 'Official' one I also see this..
-  author:  Bartek Szopka
-  version: 0.5.3
-  url:     http://bartaz.github.com/impress.js/
-  source:  http://github.com/bartaz/impress.js/

And I read deep into impress.js of your version, I see how you integration it.

```
var preInit = function() {
    if( window.markdown ){
        // particular. We do it ourselves here. In addition, we use "-----" as a delimiter for new slide.

        // Query all .markdown elements and translate to HTML
        var markdownDivs = document.querySelectorAll(".markdown");
        for (var element of markdownDivs) {

        // Note: unlike the previous two, markdown.js doesn't automatically find or convert anything in 
          var slides = element.textContent.split(/^-----$/m);
          var i = slides.length - 1;
          element.innerHTML = markdown.toHTML(slides[i]);
          // If there's an id, unset it for last, and all other, elements, and then set it for the first.
          if( element.id ){
            var id = element.id;
            element.id = "";
          }
          i--;
          while (i >= 0){
            var newElement = element.cloneNode(false);
            newElement.innerHTML = markdown.toHTML(slides[i]);
            element.parentNode.insertBefore(newElement, element);
            element = newElement;
            i--;
          }
          element.id = id;
        }
    } // markdown

    if(window.hljs){
        hljs.initHighlightingOnLoad();        
    }

    if(window.mermaid){
        mermaid.initialize({startOnLoad:true});
    }
};
```

I think that's why your markdown.js didn't work with official impress.js.

**Comment by jmecn** [comment]
This is what I did 4 days ago.
1. I download impress.js 0.6.0, copy _impress.js_ to my `script` folder.
2. Wrote a html with impress.js, and found myself tired with `<h1>` `<p>` `<div>`.
3. Search and download your fork, copy _markdown.js_ into my `script` folder too.
4. Wrote with markdown but it didn't work.

Now I know why, and it works perfect for me.
Thanks for your great work.

[Here](http://www.jmecn.net/math/) is my work, not finished yet. I'm trying to translate [this](http://wiki.jmonkeyengine.org/tutorials/math/assets/fallback/index.html) into other languages.

**Comment by henrikingo** [comment]
Ah, ok then. So, as you've discovered, writing slides in markdown will not work with the upstream/official impress.js, you need the js/impress.js from this repository. Unfortunately upstream has been quite slow in picking up new features, so I don't know when this might be included, if ever, in the official one.

Glad you've found the solution now.
